### ISSUE TITLE
Add half-size

### ISSUE THREAD

**Issue by elnexreal** [Saltssaumure/fnf-osu-mania-skin#10]
add it please

**Comment by Saltssaumure** [comment]
It's already available, see the .osk files with MiniSize in their name at https://github.com/Saltssaumure/fnf-osu-mania-skin/releases/tag/v1.5

**Comment by elnexreal** [comment]
I mean like HalfSize not minizise, like a normal size cuz minisize is too small

**Comment by Saltssaumure** [comment]
I will not be adding a third size option as it's simply too much effort for a small audience - adding another size option requires fully remaking the arrows from scratch. I'd advise using the FullSize version, along with a smaller resolution in letterboxed mode to slightly reduce overall UI size.
