### ISSUE TITLE
Everything but the arrows show up

### ISSUE THREAD

**Issue by DJDogster1384** [Saltssaumure/fnf-osu-mania-skin#2]
So, I was getting this mod because I struggled with osu!mania, and thought that this would help, I download it, do everything as instructed, and it didn't work! Everything was different, EXCEPT the arrows.

**Comment by Saltssaumure** [comment]
Hi there, thanks for trying this skin! Let's try to find what's causing the issue.

1. Firstly just to make sure, are you using the latest version, downloaded within the last 18 days, from  https://github.com/Saltssaumure/fnf-osu-mania-skin/releases/latest ?
2. What is your osu! window resolution? You can find this info in osu!'s Options > Graphics > Layout > Resolution.
3. Are you running osu! in compatibility mode?
4. Do other (non-default) osu!mania skins work correctly?

**Comment by Saltssaumure** [comment]
Closing this issue due to no response and no one else reporting this.
