### ISSUE TITLE
Arrows for 10k+

### ISSUE THREAD

**Issue by LOLZSICKA** [Saltssaumure/fnf-osu-mania-skin#31]
so uh the 5k+5k is fine but id like a skin.ini that combines the 5k+5k (and above) into one

dont got some sorta example screenshot sry

**Comment by LOLZSICKA** [comment]
also im not sure if there already exists that sorta skin.ini yet

**Comment by Saltssaumure** [comment]
If I'm understanding correctly, you would like remove the space between player 1 and player 2's keys?

To make this on any particular keycount, add the following line into that keycount's section in the `skin.ini`:
`SplitStages: 0`

For example, for 5K+5K -> 10K:
![image](https://user-images.githubusercontent.com/29710355/142483350-ef4fc69f-f6f4-40ea-950d-5c0242f99428.png)

![image](https://user-images.githubusercontent.com/29710355/142483109-a7b0c588-2445-45ec-9801-c1bef5dc64a2.png)

**Comment by LOLZSICKA** [comment]
i do know how to do the splitstages thing but like i was asking for some
sorta separate skin.ini for if anyone wants a more readable layout for 10k+

>

**Comment by Saltssaumure** [comment]
As this is quite niche (people generally do not play with more than their number of fingers), and given that these modes are intended to be co-op, I will not be releasing a separate skin.ini for this purpose. Thanks for your feedback though!
