### ISSUE TITLE
How to download

### ISSUE THREAD

**Issue by Striky08** [Saltssaumure/fnf-osu-mania-skin#32]
Very sorry if this isn't really an issue in the game sort thing its just that I've never actually downloaded anything off of GitHub and  yeah I was wondering if someone would tell me how to download something off of GitHub thanks :)

**Comment by Saltssaumure** [comment]
1. Go here to see the latest release: https://github.com/Saltssaumure/fnf-osu-mania-skin/releases/latest
2. Scroll down to the `Assets` section.
3. Choose one/any of the `.osk` files - the filename describes what that skin variation looks like.
4. Click that file's link to download.
