### ISSUE TITLE
Make 6k/7k vs. shaggy style

### ISSUE THREAD

**Issue by MegaGamer22** [Saltssaumure/fnf-osu-mania-skin#33]

**Comment by Saltssaumure** [comment]
These already exist.
![image](https://user-images.githubusercontent.com/29710355/144661082-6d1121e7-c715-4625-b4b8-e51aa0a44422.png)
![image](https://user-images.githubusercontent.com/29710355/144661203-2749b0c2-3009-4959-9844-e03bc785d983.png)
