### ISSUE TITLE
Where is downscroll option?

### ISSUE THREAD

**Issue by chiception** [Saltssaumure/fnf-osu-mania-skin#4]
I can't find the downscroll option even if there is one, i've looked all in settings and couldn't find it.

**Comment by Electrized** [comment]
Hey, for you (and anyone else stumbling upon this later) You can enable downscroll by going into your mania keybinds and enabling / disabling "Vertically Flip Playfield" 
![image](https://user-images.githubusercontent.com/29844497/114715406-b7f74900-9d3b-11eb-9cec-dcb77956e94e.png)

**Comment by Electrized** [comment]
Also as far as i know, if your other skins are already downscrolling you can also change it from skin.ini by changing the line:
UpsideDown: 1

to read

UpsideDown: 0

However, I'm not sure if it would break some of the visuals  (particularly the arrows), try out for yourself

**Comment by Saltssaumure** [comment]
Both of these are good working solutions. If the skin seems misaligned after flipping to downscroll, please download the latest version (the early versions did not support downscroll).

Pinning this issue for future users' reference.

**Comment by ThatOneCalculator** [comment]
Why is this issue still open lmfao

**Comment by Saltssaumure** [comment]
If you are only able to enable downscroll on one keymode (eg. 4K only), see #29 for the solution.
