### ISSUE TITLE
The 6 and 7 key sets are wrong

### ISSUE THREAD

**Issue by astro1354** [Saltssaumure/fnf-osu-mania-skin#40]
The 6 key and 7 key sets are supposed to be
LEFT UP RIGHT LEFT DOWN RIGHT and LEFT UP RIGHT CRYSTAL LEFT DOWN RIGHT, instead of how you put them.

**Comment by Saltssaumure** [comment]
Feel free to edit the `Skin.ini` file for your preferred arrow order:

1. Open `Skin.ini` using a text editor (I recommend Notepad++, though regular Notepad also works)
2. Find the section for the keymode you wish to edit.
3. Under that section, find the part where each line starts with `KeyImage` and `NoteImage`.
4. Change the last part of those lines to whichever direction arrow you want, or `crystal`.
5. Save file and reload skin in osu! (Ctrl + Alt + Shift + S) to view your changes.

**Comment by astro1354** [comment]
I did that but it didn’t change at all, even when I pressed Ctrl + Alt + Shift + S

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
