### ISSUE TITLE
Down scroll not working

### ISSUE THREAD

**Issue by osumaniabegineer** [Saltssaumure/fnf-osu-mania-skin#5]
my down scroll cant play galaxy collapse 4k please help me

**Comment by gaster100** [comment]
Yo no se como activarlo ._.

**Comment by Saltssaumure** [comment]
Have you tried the downscroll instructions in the README.md? Could you describe the problem in a bit more detail please?

**Comment by Saltssaumure** [comment]
Closed due to inactivity (also duplicate of #4 if solution worked)
